### PR TITLE
remove dependency on 'window', declare missing variable

### PR DESCRIPTION
**Pull request by sedenardi**
In order to make this plugin work with server-side rendering, I've removed the dependency on `window` by declaring it when it detects a server environment (when `module` is declared) and skips the `hasOwnProperty` call when it is undefined.

I've also declared `tRatio` which was previously just using a global variable.

### CODE REVIEW

**Comment by sedenardi** [comment]
Also, have you considered publishing this lib to npm?

**Comment by aullman** [comment]
Thanks @sedenardi. It is on npm https://www.npmjs.com/package/opentok-layout-js

**Comment by aullman** [comment]
What server-side rendering are you using this for btw? What's the use-case? Is this for archiving? I am interested.

**Comment by sedenardi** [comment]
@aullman Thanks for this. 

I'm using Nodejs + Reactjs in my application. I render the markup on the server so that there's no perceivable load times to the user (as opposed to most single-page applications where you send the markup for a container and the page is only fully loaded once all the JS files are downloaded). For this and other 3rd party libraries, I have to make safe references to `window` because `window` doesn't exist when rendering on the server, only `document` does. This usually isn't an issue, as most libs only do DOM manipulation and don't write global variables.

**Comment by aullman** [comment]
Ah, that makes sense, cool, thanks.

**Comment by sedenardi** [comment]
@aullman Note, b7d1b5c351268d5a3b673d61b3b17052ba99d76f broke this fix, as `window` is now undefined on the server again.

I'm getting around this by adding a shim before requiring the lib:
```
if (!global.window) { global.window = null; }
var OpenTokLayout = require('opentok-layout-js');
```
Not a bug per se, but thought you should be aware (and maybe add a note in the README, but not a huge deal).

**Comment by aullman** [comment]
Bummer, sorry about this. Feel free to submit a PR that fixes this issue. The problem I had was that IE10 was complaining when I was defining a `window` variable even though window wasn't getting used in IE10 context.

Actually a quick fix would just be to call it win instead of window, I might do that now. I should probably also add a test that includes the file in node to make sure it's working.

**Pull request merged**
