### PR TITLE
[Issues/90] margin padding fix

### LINKED ISSUE #90: Padding, Border, and Margin not taken into account due to camelCase CSS property names
The layout should take into account border, padding and margin as stated in the [readme](https://github.com/aullman/opentok-layout-js#padding-margins-and-borders).
However this is not working. It appears to be due to the css properties being in cameCasel e.g. here https://github.com/aullman/opentok-layout-js/blob/master/opentok-layout.js#L691

I wrote this test html page and opened it on a few browsers. None seemed to support these properties in camelCase format.

```
<html>
  <head>
    <style>
      .my-element {
        border-top: 1px;
        border-bottom: 2px;
        padding-top: 2px;
        margin-top: 3px;
      }
    </style>
  </head>
  <body>
    <div id="myElement" class="my-element">
    </div>
    <script type="text/javascript">
      const myElement = document.getElementById('myElement');
      const computedStyle = getComputedStyle(myElement);
    const checkCssPropName = (propName) => {
      const value = computedStyle.getPropertyValue(propName);
      console.log(`${propName}: ${value}`);
    }

    const propNames = [
      'borderTop',
      'border-top',
      'marginTop',
      'margin-top',
      'paddingTop',
      'padding-top',
    ];
    propNames.forEach(checkCssPropName);
    </script>
  </body>
</html>

```

### PR DESCRIPTION
**Pull request by maikthomas**
Fixes #90

### CODE REVIEW

**Comment by aullman** [comment]
We actually have tests for this but I see they were failing because we were fallling back to just checking, `element.style['paddingRight']` etc which does work and the tests were setting the style directly on the element. 

You're editing the wrong file here though. The opentok-layout file is generated by webpack. I'll update it to the right underlying file.

**Comment by aullman** [comment]
Thanks for catching this one @maikthomas !!

**Comment by aullman** [comment]
I'm going to release this as a major version update because otherwise people using the library might have very different behaviour all of a sudden.

**Comment by maikthomas** [comment]
Ah of course, wrong file sorry 🤦 
Thanks updating it 🙌

**Pull request merged**
