### PR TITLE
Modify to not require OpenTok library being loaded

### PR DESCRIPTION
**Pull request by ggarber**
Add support to use jQuery CSS helpers instead of OpenTok CSS helpers if OpenTok library is not loaded.

Tests: Unit tests with and without loading opentok.js in index.html pass.

Open Issue: Generate minimized version of the library.  Is there any npm task to do that?

### CODE REVIEW

**Comment by aullman** [comment]
Thanks for the contribution! I've been meaning to do that. Actually meaning to just remove the opentok requirement altogether. This will do for now though.

The unit tests are failing because they're using a really old version of node. I just updated the node version in .travis.yml in the master branch. If you pull that in it should start passing. 

You can generate the minified version by just running `gulp` or `npx gulp` if you don't have it already installed globally.

**Comment by ggarber** [comment]
Thx @aullman   Tests passes in Chrome now.  They still fail in Saucelabs but I think it is a problem with the APIKey, so feel free to merge this if you think it is useful.    I love this library and plan to use it for an internal testing webpage.   Thx!

**Comment by aullman** [comment]
Ah yes Travis encrypted variables only work in the same repo. I'll merge and keep an eye that they pass and then publish a new version to npm.

**Comment by aullman** [comment]
Actually I did some testing and there are a few more changes needed to get this to work without opentok. There is an OT.load in there still and also some of the JQuery functions don’t behave exactly the same. I can have a go at cleaning it up next week hopefully.

**Comment by ggarber** [comment]
I run the tests removing opentok.js and the tests passed :( . If you want to point me to those jquery inconsistencies I can take a look.

**Comment by aullman** [comment]
I made some progress and submitted a separate PR https://github.com/aullman/opentok-layout-js/pull/39

Some tests are still failing...

**Pull request merged**
